#!/bin/bash
# Updates the project's Visual/Eclipse compatibility links
# Needs file : ${HOME}/.updateEclipse

SCRIPT_NAME=$(basename $0)

# Error logging function
function error()
{
	echo "${SCRIPT_NAME}: $@" 1>&2
}

# Data check.
if (( $# > 0 ))
then
	error 'Error. No argument needed.'
	exit 1
fi

source ${HOME}/.updateEclipse

for NEWFILE in $(cd ${ECDIR};find . -regextype 'posix-egrep' -type f -regex '.*\.(cpp|h)')
do
	echo "Added : $NEWFILE"
	mv ${ECDIR}/$NEWFILE ${VSDIR}/$NEWFILE
done

rm -f ${ECDIR}/*{.cpp,.h} 1>/dev/null 2>&1
for FILE in $(cd ${VSDIR}; ls *{\.cpp,\.h} 2>/dev/null)
do
	ln -s ${VSDIR}/${FILE} ${ECDIR}/${FILE}
done

exit 0

